# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import trainer_pb2 as trainer__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in trainer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrainerServiceStub(object):
    """─────────────────────────────────────────────
    Service definition
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/trainer.TrainerService/Register',
                request_serializer=trainer__pb2.RegisterRequest.SerializeToString,
                response_deserializer=trainer__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.stream_stream(
                '/trainer.TrainerService/Heartbeat',
                request_serializer=trainer__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=trainer__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.GetAssignment = channel.unary_unary(
                '/trainer.TrainerService/GetAssignment',
                request_serializer=trainer__pb2.GetAssignmentRequest.SerializeToString,
                response_deserializer=trainer__pb2.GetAssignmentResponse.FromString,
                _registered_method=True)
        self.ExchangeGradients = channel.unary_unary(
                '/trainer.TrainerService/ExchangeGradients',
                request_serializer=trainer__pb2.GradientPush.SerializeToString,
                response_deserializer=trainer__pb2.WeightUpdate.FromString,
                _registered_method=True)
        self.GetClusterStatus = channel.unary_unary(
                '/trainer.TrainerService/GetClusterStatus',
                request_serializer=trainer__pb2.ClusterStatusRequest.SerializeToString,
                response_deserializer=trainer__pb2.ClusterStatusResponse.FromString,
                _registered_method=True)
        self.AdmitWorkers = channel.unary_unary(
                '/trainer.TrainerService/AdmitWorkers',
                request_serializer=trainer__pb2.AdmitWorkersRequest.SerializeToString,
                response_deserializer=trainer__pb2.AdmitWorkersResponse.FromString,
                _registered_method=True)


class TrainerServiceServicer(object):
    """─────────────────────────────────────────────
    Service definition
    ─────────────────────────────────────────────

    """

    def Register(self, request, context):
        """Worker calls once on startup to announce itself
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request_iterator, context):
        """Bidirectional heartbeat: worker streams status, leader streams commands
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAssignment(self, request, context):
        """Worker calls after registering; BLOCKS until leader starts training,
        then returns shard assignment + config + initial model weights
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExchangeGradients(self, request, context):
        """Worker pushes compressed gradients; leader aggregates, returns weight delta
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClusterStatus(self, request, context):
        """Dashboard / monitoring query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdmitWorkers(self, request, context):
        """Admit one or more pending workers into the active training run
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=trainer__pb2.RegisterRequest.FromString,
                    response_serializer=trainer__pb2.RegisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.stream_stream_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=trainer__pb2.HeartbeatRequest.FromString,
                    response_serializer=trainer__pb2.HeartbeatResponse.SerializeToString,
            ),
            'GetAssignment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssignment,
                    request_deserializer=trainer__pb2.GetAssignmentRequest.FromString,
                    response_serializer=trainer__pb2.GetAssignmentResponse.SerializeToString,
            ),
            'ExchangeGradients': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangeGradients,
                    request_deserializer=trainer__pb2.GradientPush.FromString,
                    response_serializer=trainer__pb2.WeightUpdate.SerializeToString,
            ),
            'GetClusterStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClusterStatus,
                    request_deserializer=trainer__pb2.ClusterStatusRequest.FromString,
                    response_serializer=trainer__pb2.ClusterStatusResponse.SerializeToString,
            ),
            'AdmitWorkers': grpc.unary_unary_rpc_method_handler(
                    servicer.AdmitWorkers,
                    request_deserializer=trainer__pb2.AdmitWorkersRequest.FromString,
                    response_serializer=trainer__pb2.AdmitWorkersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trainer.TrainerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trainer.TrainerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrainerService(object):
    """─────────────────────────────────────────────
    Service definition
    ─────────────────────────────────────────────

    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trainer.TrainerService/Register',
            trainer__pb2.RegisterRequest.SerializeToString,
            trainer__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/trainer.TrainerService/Heartbeat',
            trainer__pb2.HeartbeatRequest.SerializeToString,
            trainer__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAssignment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trainer.TrainerService/GetAssignment',
            trainer__pb2.GetAssignmentRequest.SerializeToString,
            trainer__pb2.GetAssignmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExchangeGradients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trainer.TrainerService/ExchangeGradients',
            trainer__pb2.GradientPush.SerializeToString,
            trainer__pb2.WeightUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClusterStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trainer.TrainerService/GetClusterStatus',
            trainer__pb2.ClusterStatusRequest.SerializeToString,
            trainer__pb2.ClusterStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdmitWorkers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trainer.TrainerService/AdmitWorkers',
            trainer__pb2.AdmitWorkersRequest.SerializeToString,
            trainer__pb2.AdmitWorkersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
